apiVersion : apps/v1
kind: Deployment
metadata:
  name: authorizationmicroservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorizationmicroservice
  template:
    metadata:
      labels:
        app: authorizationmicroservice 
    spec:
      containers:
        - name: authorizationmicroservice 
          image: pensionsystem.azurecr.io/authorizationmicroservice
          ports:
          - containerPort: 80