apiVersion: apps/v1
kind: Deployment
metadata:
  name: pensionerdetailmicroservice-deployment
  labels:
    app: pensionerdetailmicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pensionerdetailmicroservice
  template:
    metadata:
      labels:
        app: pensionerdetailmicroservice
    spec:
      containers:
        - name: pensionerdetailmicroservice
          image: pensionsystem.azurecr.io/pensionerdetailmicroservice:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pensionerdetailmicroservice-service
spec:
  type: LoadBalancer
  selector:
    app: pensionerdetailmicroservice
  ports:
    - protocol: TCP
      port: 80