// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessPensionMicroservice.Data;

namespace ProcessPensionMicroservice.Migrations
{
    [DbContext(typeof(ApplicationDbContex))]
    [Migration("20220701090403_processPensionTable")]
    partial class processPensionTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PensionerDetailMicroservice.Model.PensionDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AadharNo")
                        .HasColumnType("bigint");

                    b.Property<long>("AccountNo")
                        .HasColumnType("bigint");

                    b.Property<int>("Allowances")
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PAN")
                        .HasColumnType("bigint");

                    b.Property<string>("PensionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalaryEarned")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PensionDetails");
                });

            modelBuilder.Entity("ProcessPensionMicroservice.Model.ProcessPension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankServiceCharge")
                        .HasColumnType("int");

                    b.Property<int>("PensionAmount")
                        .HasColumnType("int");

                    b.Property<int>("PensionDetailsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PensionDetailsId");

                    b.ToTable("processPensions");
                });

            modelBuilder.Entity("ProcessPensionMicroservice.Model.ProcessPension", b =>
                {
                    b.HasOne("PensionerDetailMicroservice.Model.PensionDetails", "PensionDetail")
                        .WithMany()
                        .HasForeignKey("PensionDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PensionDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
