// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessPensionMicroservice.Data;

namespace ProcessPensionMicroservice.Migrations
{
    [DbContext(typeof(ApplicationDbContex))]
    [Migration("20220701103616_updateProcessPension")]
    partial class updateProcessPension
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProcessPensionMicroservice.Model.ProcessPension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddharId")
                        .HasColumnType("int");

                    b.Property<int>("BankServiceCharge")
                        .HasColumnType("int");

                    b.Property<int>("PensionAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("processPensions");
                });
#pragma warning restore 612, 618
        }
    }
}
